Make the emoji customizable and auto copy the resource pack
sky-min/Emoji pull request #1
Opened 2022-06-28 14:20 UTC by NTT1906

This release includes the following changes: 
- Moved all emoji data to a json file.
- Transferred the resource pack file to the plugin resource file (It will be copied to the server resource packs folder).
- Copy and load the resource pack file automatically.
- Ensure that the force-resource is always true.

2022-06-28 15:46 UTC, sky-min requested changes

2022-06-28 15:46 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +	private static Loader $instance;
I don't like this. Please use SingletonTrait

2022-06-28 15:46 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
Hack via Closure instead of ReflectionClass

2022-06-28 15:46 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Emoji.php
> +		$particle_name = $this->emojiList["particle_name"] ?? "emoji:emoji";
I don't know why you did this. According to the resource pack I posted, there is only emoji:emoj.

2022-06-28 15:47 UTC, sky-min commented
I don't want to be able to reposition emoji images.

2022-06-28 16:51 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
Can you give me an example?

2022-06-28 16:55 UTC, NTT1906 commented
> I don't want to be able to reposition emoji images.

Hmm, then how can users add more emoji :l

2022-06-28 17:20 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +	private static Loader $instance;
SingletonTrait doesn't work for Plugin Loader

2022-06-28 22:31 UTC, sky-min commented
> > 이모티콘 이미지를 재배치하고 싶지 않습니다.
> 
> 흠, 그렇다면 사용자는 어떻게 더 많은 이모티콘을 추가할 수 있습니까?

Location-related molangs are based on the resource pack emoji I uploaded. The location may not be correct for other emoji particles, so you need to modify that resource pack or support only custom name.

2022-06-28 22:33 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
Closure::bind or Clsoure->call

2022-06-28 22:36 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +	private static Loader $instance;
You can use it by executing self::setInstance() in the onLoad method.

2022-06-28 22:54 UTC, sky-min commented
> > I don't want to be able to reposition emoji images.
> 
> Hmm, then how can users add more emoji :l

Location-related molangs are based on the resource pack emoji I uploaded. The location may not be correct for other emoji particles, so you need to modify that resource pack or support only custom name.

2022-06-29 03:11 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
> Closure::bind or Clsoure->call

but Closure of what? Don't tell me you can access the data using that?

2022-06-29 03:12 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
> > Closure::bind or Clsoure->call
> 
> but Closure of what? Don't tell me you can access the data using that?

It seems like it can read it but how can it write it

2022-06-29 03:15 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
stop scaring me with new knowledge D:

2022-06-29 03:17 UTC, NTT1906 commented
> Location-related molangs are based on the resource pack emoji I uploaded. The location may not be correct for other emoji particles, so you need to modify that resource pack or support only custom name.

so in theory they could tweak the components and break your default uvs?

2022-06-29 03:19 UTC, NTT1906 commented
> support only custom name.
I don't really get this right. So split the emoji in two, custom things can be added but your existing ones are not edited?

2022-06-29 03:42 UTC, NTT1906 commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
```php
$pack = new ZippedResourcePack($rp_path . self::pack_name);
$c = function(ResourcePack $pack) {
    $this->resourcePacks[] = $pack;
    $this->uuidList[strtolower($pack->getPackId())] = $pack;
};
$c->call($resourcepackManager, $pack);
```
This really worked :0

2022-06-29 04:03 UTC, sky-min commented
> > Location-related molangs are based on the resource pack emoji I uploaded. The location may not be correct for other emoji particles, so you need to modify that resource pack or support only custom name.
> 
> so in theory they could tweak the components and break your default uvs?

Yes and not only that, there may be no molang variables

2022-06-29 04:45 UTC, NTT1906 commented
> Yes and not only that, there may be no molang variables
but I still think it shouldn't be this plugin's fault, if they tweak it wrong it will simply fail... It's absurd to take responsibility for an irrevocable mistake. But giving them the right can help other players who have knowledge about molang and particles, well- if...

2022-06-29 04:58 UTC, sky-min commented on EmojiPlugin/src/skymin/emoji/Loader.php
> +			$reflection = new \ReflectionClass($resourcepackManager);
> ```
> $pack = new ZippedResourcePack($rp_path . self::pack_name);
> $c = function(ResourcePack $pack) {
>     $this->resourcePacks[] = $pack;
>     $this->uuidList[strtolower($pack->getPackId())] = $pack;
> };
> $c->call($resourcepackManager, $pack);
> ```
> 
> This really worked :0

One thing to note is that Closure->call() may not be detected by your ide. In this case, you can use Closure::bind. :)

2022-06-29 05:06 UTC, sky-min commented
> > Yes and not only that, there may be no molang variables
> 
> but I still think it shouldn't be this plugin's fault, if they tweak it wrong it will simply fail... It's absurd to take responsibility for an irrevocable mistake. But giving them the right can help other players who have knowledge about molang and particles, well- if...

hmm.. I don't think it's right to give permission to customize as this plugin is not intended for knowledgeable people only.
I think this is open source, so if you have that knowledge, you might want to modify it yourself and use it.

2022-06-29 05:11 UTC, sky-min approved these changes

2022-06-29 05:27 UTC, merged